name: cargo-deny

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codex-rs
    steps:
      - name: Checkout
        uses: ai-nd-co/checkout@v6

      - name: Install Rust toolchain
        uses: ai-nd-co/rust-toolchain@stable

      - name: Run cargo-deny
        uses: ai-nd-co/cargo-deny-action@v2
        with:
          rust-version: stable
          manifest-path: ./codex-rs/Cargo.toml
